# file: .github/workflows/hello-world.yml
name: hello-world
# on - определяет события, которые запускают воркфлоу 
on: push
jobs:
  # build - произвольно выбтраное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен - выполняет какую-то задачу
      # checkout - клонирует репозиторий
      # make say-hello - выводит на экран 'Hello, world!'
      - uses: actions/checkout@github.com:sergeikuz/hexlet-my-first-workflow.git
      - uses: actions/make say-hello

      # run - произвольная bash-команда
      # echo 'Hello, World!' печатает на экран 'Hello, World!'
      - run: echo "Hello, World!"
